apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec: # resource specification
  selector: # Selector which SelectorMonitor will be find to be used as service monitoring
    matchLabels: #Label to be used on monitoring by ServiceMonitor
      app: nginx
  replicas: 3
  template: # will be used to create pods
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec: #Template specification
      containers:
        - name: nginx # container name that will be created on the Pod.
          image: nginx 
          ports:
            - containerPort: 80
              name: http
          volumeMounts: # volume that will be mounted on container
            - name: nginx-config # name of volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf 
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.11.0' #image specific to nginx exporter
          args: 
            - '-nginx.scrape-uri=http://localhost/metrics' # argument to define URI scrapping   
          resources:
            limits:
              memory: 128Mi
              cpu: 0.3
          ports:
            - containerPort: 9113 #port to be exposed
              name: metrics
      volumes:
        - configMap:
            defaultMode: 420 #default mode of volume
            name: nginx-config
          name: nginx-config     